/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uitech;
import java.awt.*;
import java.net.*;
import java.io.*;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author S K RAI
 */
public class GUi extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form GUi
     */
    ServerSocket ss;
    static Socket s;
    InetAddress i;
    BufferedReader r;
    BufferedWriter out;
    String rec;
    Thread t;
     PrintWriter pw;
     String add;
     int portn;
     Color initColor;
     
    
     public GUi(int c)
     {
         initComponents();
        
        try{
            ss = new ServerSocket(c);
            status.setText("Waiting");
             System.out.println("Server  ready for chatting");
             
             i = InetAddress.getLocalHost();
            s = ss.accept();
            
            
            status.setText("CONNECTED");
            user.setText("SERVER");
            client.setText(i.getHostAddress());
            port.setText(Integer.toString(c));
            
            r = new BufferedReader(new InputStreamReader(s.getInputStream()));
             pw=new PrintWriter(s.getOutputStream(),true);
            t = new Thread(this);
            t.setDaemon(true);
            t.start();
        }catch(IOException e)
        {
            
        }
     }
    public GUi(String add1,int p) {
        initComponents();
        add = add1;
        portn  = p;
        try{
            s = new Socket(add,p);
            status.setText("CONNECTED");
            user.setText("CLIENT");
            client.setText(add);
            port.setText(Integer.toString(p));
            r = new BufferedReader(new InputStreamReader(s.getInputStream()));
             pw=new PrintWriter(s.getOutputStream(),true);
            t = new Thread(this);
            t.setDaemon(true);
            t.start();
        }catch(IOException e)
        {
            status.setText("NOT CONNECT");
            client.setText(add);
            port.setText(Integer.toString(p));
        }
        
    }
//@Override
public void run()
{
    while(true)
    {
        try{
            System.out.println("hello");
             rec = r.readLine();
           // chatArea.setForeground(Color.red);
            chatArea.append("\nFriend :"+rec);
            Thread.sleep(1000);
        }catch(IOException e)
        {
            status.setText("NOT CONNECT");
        }catch(InterruptedException e)
        {
            status.setText("ERROR");
        }
        
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        chat = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        roundl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        off = new javax.swing.JButton();
        setting = new javax.swing.JButton();
        client = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        ul = new javax.swing.JLabel();
        up = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        photo = new javax.swing.JButton();
        clearChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChatChat");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(2, 70, 105));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(204, 0, 204));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        chatArea.setEditable(false);
        chatArea.setBackground(new java.awt.Color(211, 88, 88));
        chatArea.setColumns(20);
        chatArea.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        chatArea.setForeground(new java.awt.Color(255, 255, 255));
        chatArea.setRows(5);
        chatArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(102, 102, 102), null, null));
        jScrollPane1.setViewportView(chatArea);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 380, 300));

        chat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chat.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 102))));
        chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatActionPerformed(evt);
            }
        });
        jPanel3.add(chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 360, 60));

        send.setBackground(new java.awt.Color(211, 88, 88));
        send.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        send.setForeground(new java.awt.Color(255, 255, 255));
        send.setText("        Send");
        send.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(2, 70, 105), java.awt.Color.black, new java.awt.Color(2, 70, 105), java.awt.Color.black));
        send.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        send.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel3.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 150, 30));

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 102, 31));

        roundl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uitech/logp2.png"))); // NOI18N
        roundl.setText("jLabel2");
        roundl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(roundl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 110));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uitech/4740737-wallpaper-blur.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 178));

        off.setBackground(new java.awt.Color(211, 88, 88));
        off.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uitech/icons8_Shutdown_32px.png"))); // NOI18N
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });
        jPanel3.add(off, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 373, 50, 50));

        setting.setBackground(new java.awt.Color(211, 88, 88));
        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uitech/icons8_Settings_32px_1.png"))); // NOI18N
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        jPanel3.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 373, 50, 50));

        client.setFont(new java.awt.Font("OldNewspaperTypes", 1, 18)); // NOI18N
        client.setText("Client");
        client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientActionPerformed(evt);
            }
        });
        jPanel3.add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 256, 168, 28));

        port.setFont(new java.awt.Font("OldNewspaperTypes", 0, 18)); // NOI18N
        port.setText("Port");
        jPanel3.add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 168, 30));

        ul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uitech/icons8_customer_32px.png"))); // NOI18N
        jPanel3.add(ul, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 256, -1, 28));

        up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uitech/icons8_Marker_16px_1.png"))); // NOI18N
        jPanel3.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 306, -1, 26));

        status.setBackground(new java.awt.Color(211, 88, 88));
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("jTextField1");
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 130, 30));

        photo.setBackground(new java.awt.Color(211, 88, 88));
        photo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        photo.setForeground(new java.awt.Color(255, 255, 255));
        photo.setText("Photo");
        photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoActionPerformed(evt);
            }
        });
        jPanel3.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 130, -1));

        clearChat.setBackground(new java.awt.Color(211, 88, 88));
        clearChat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearChat.setForeground(new java.awt.Color(255, 255, 255));
        clearChat.setText("Clear");
        clearChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearChatActionPerformed(evt);
            }
        });
        jPanel3.add(clearChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 130, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatActionPerformed
        // TODO add your handling code here:
        // chatArea.setForeground(Color.BLACK);
        chatArea.append("\nYOU :"+chat.getText());
         pw.println(chat.getText());
        
        chat.setText("");
    }//GEN-LAST:event_chatActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        chatArea.setForeground(Color.BLACK);
        chatArea.append("\nYOU :"+chat.getText());
        pw.println(chat.getText());
           chat.setText("");
    }//GEN-LAST:event_sendActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
initColor = JColorChooser.showDialog(this,"Select Chat Area Color",new Color(211, 88, 88));
        chatArea.setBackground(initColor); 
        send.setBackground(initColor);
initColor = JColorChooser.showDialog(this,"COLOR OF TEXT",chatArea.getForeground());
          chatArea.setForeground(initColor);
        
// TODO add your handling code here:\popS.show(setting,setting.getBounds().x,setting.getBounds().y+setting.getBounds().height);
    }//GEN-LAST:event_settingActionPerformed

    private void photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int i = fc.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION)
        {
            File f = fc.getSelectedFile();
            String filepath = f.getPath();
            
           try {
               roundl.setIcon(new ImageIcon(filepath));
               roundl.revalidate();
               roundl.repaint();
           }catch(Exception e)
           {
               
           }
            
        }
    }//GEN-LAST:event_photoActionPerformed

    private void clearChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearChatActionPerformed
        // TODO add your handling code here:
        chatArea.setText("");
    }//GEN-LAST:event_clearChatActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        // TODO add your handling code here:
        Start sop = new Start();
          sop.setVisible(true);
        dispose();
    }//GEN-LAST:event_offActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chat;
    private javax.swing.JTextArea chatArea;
    private javax.swing.JButton clearChat;
    private javax.swing.JTextField client;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton off;
    private javax.swing.JButton photo;
    private javax.swing.JTextField port;
    private javax.swing.JLabel roundl;
    private javax.swing.JButton send;
    private javax.swing.JButton setting;
    private javax.swing.JTextField status;
    private javax.swing.JLabel ul;
    private javax.swing.JLabel up;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
